#!/usr/bin/env python3
"""Assemble the FZGM RQ4 (light-source ROIBIN) evidence artifact from raw results.

Inputs (this directory):
  clean_timing_results_{EXAFEL,CXIDB21}_a062d88.json   FZGM variants, staged/specialized
  native_{DS}_bin{1,2}_{serial,frames20}.json          native ROIBIN-SZ (LibPressio/SZ3)
  baselines_volume_{DS}.json                           general GPU compressors, global eb
Outputs:
  <out>/roibin_rq4.json   (consumed by papers/FZGM/scripts/plot_roibin_frontier.py)
  <out>/roibin_rq4.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REV = "a062d88"
CORPORA = {"EXAFEL": "EXAFEL (LCLS, 130 frames, calibrated)",
           "CXIDB21": "CXIDB 21 (LCLS, 279 frames, raw ADU)"}
# Figure selection: specialized configurations plus the best-ratio staged coders.
# Golomb-Rice (H_diff_golomb) is omitted from the figure: compression-only specialization,
# dominated by Bitpack; it stays in fzgm_all.
FIG_VARIANTS = {"A_bitpack": "Bitpack", "G_pfpl": "PFPL back end",
                "E_tl_huff16": "Huffman", "F_tl_rze_ans16": "RZE+ANS", "I_ginterp_cr": "Interp"}
LABELS = {"A_bitpack": "TiledLorenzo-AdaptiveBitpack",
          "B_golomb_tl": "TiledLorenzo-GolombRice",
          "C_tl_rze": "TiledLorenzo-Zigzag-Bitshuffle-RZE",
          "D_tl_rze_ans": "TiledLorenzo-Zigzag-Bitshuffle-RZE-ANS (32-bit)",
          "E_tl_huff16": "TiledLorenzo-Zigzag-Huffman (16-bit)",
          "F_tl_rze_ans16": "TiledLorenzo-Zigzag-Bitshuffle-RZE-ANS (16-bit)",
          "G_pfpl": "Quantizer-Difference-Bitshuffle-RZE (PFPL back end)",
          "H_diff_golomb": "Quantizer-Difference-GolombRice",
          "I_ginterp_cr": "GInterp-Huffman-Merge-RRE-Zigzag-RZE (cuSZ-Hi CR back end; bin=1 only)"}
BASELINE_LABELS = {"PFPL": "PFPL", "cuSZp3 plain 2-D": "cuSZp3", "cuSZ-Hi (spline/cr-first/cr)": "cuSZ-Hi",
                   "cuSZ": "cuSZ"}


def load(name):
    return json.loads((HERE / name).read_text())


def main(out: Path) -> None:
    payload = {"revision": REV, "eb_roi_abs": 10.0, "eb_bg_abs": 100.0, "roi_box": "9x9",
               "platform": "H100 80GB HBM3 (Jetstream2), clocks locked; CPU Xeon 8468, 20 cores",
               "corpora": []}
    md = [f"# RQ4 light-source evidence: ROIBIN in FZGM vs native ROIBIN-SZ and general GPU compressors",
          "", f"FZGPUModules `{REV}`. Generated by `compression_benchmarking/case_studies/roibin/"
          "native_roibin_sz/build_rq4_artifact.py`; see `NOTES.md` there for protocol and history.", ""]
    for ds, title in CORPORA.items():
        rows = load(f"clean_timing_results_{ds}_{REV}.json")
        rows += load(f"clean_timing_results_{ds}_{REV}_ginterp.json")   # GInterp variant, same build/protocol
        for r in rows:
            assert r["ident"], (ds, r["variant"], "staged/specialized reconstructions differ")
            assert r["roi_max"] <= 10.0 * 1.001, (ds, r["variant"], "ROI bound")
            if r["bin"] == 1:
                assert r["bg_max"] <= 100.0 * 1.001, (ds, r["variant"], "background bound")
        nat = {b: {m: load(f"native_{ds}_bin{b}_{m}.json")["summary"] for m in ("serial", "frames20")}
               for b in (1, 2)}
        base = load(f"baselines_volume_{ds}.json")
        corpus = {"dataset": ds, "title": title, "fzgm": [], "fzgm_all": [], "general_gpu": [],
                  "general_gpu_excluded": []}
        for r in rows:
            spec = r["inst"][0] > 0
            entry = dict(variant=r["variant"], name=LABELS[r["variant"]], bin=r["bin"], cr=r["cr_off"],
                         compress_gbs_staged=r["C_off"], decompress_gbs_staged=r["D_off"],
                         compress_gbs_specialized=r["C_auto"], decompress_gbs_specialized=r["D_auto"],
                         specialized=spec, installed_groups=r["inst"], implementation=r["impl"],
                         roi_max_err=r["roi_max"], bg_max_err=r["bg_max"], bg_psnr=r["bg_psnr"],
                         max_phase_cv=max(r["cv_off"], r["cv_auto"]))
            corpus["fzgm_all"].append(entry)
            if r["bin"] == 1 and r["variant"] in FIG_VARIANTS:
                corpus["fzgm"].append(dict(entry, label=FIG_VARIANTS[r["variant"]]))
        n1s, n1p = nat[1]["serial"], nat[1]["frames20"]
        corpus["native_roibin_sz"] = dict(
            bin=1, cr=n1s["agg_cr"], cr_with_peak_table=n1s["agg_cr_with_peak_table"],
            compress_gbs_1core=n1s["agg_cmp_gbs"], decompress_gbs_1core=n1s["agg_dec_gbs"],
            compress_gbs_20core=20 * n1p["agg_cmp_gbs"], decompress_gbs_20core=20 * n1p["agg_dec_gbs"],
            wall_bound_gbs_20core=n1p["frames_wall_codec_gbs"],
            roi_max_err=n1s["roi_max_err"], bg_max_err=n1s["bg_max_err"])
        # ROIBIN-SZ's composition with a no-op inner compressor: LibPressio roibin's
        # CPU-side peak gather/split cost alone, i.e. the ceiling for ANY inner
        # compressor (CPU or GPU) inside that composition on this node.
        noop_s = load(f"native_{ds}_bin1_serial_noopoutlier.json")["summary"]
        noop_p = load(f"native_{ds}_bin1_frames20_noopoutlier.json")["summary"]
        corpus["roibin_sz_composition_ceiling"] = dict(
            compress_gbs_1stream=noop_s["agg_cmp_gbs"], decompress_gbs_1stream=noop_s["agg_dec_gbs"],
            compress_gbs_20core=20 * noop_p["agg_cmp_gbs"], decompress_gbs_20core=20 * noop_p["agg_dec_gbs"])
        corpus["native_roibin_sz_bin2"] = dict(
            cr=nat[2]["serial"]["agg_cr"], compress_gbs_1core=nat[2]["serial"]["agg_cmp_gbs"],
            compress_gbs_20core=20 * nat[2]["frames20"]["agg_cmp_gbs"])
        for b in base:
            if "error" in b:
                corpus["general_gpu_excluded"].append(dict(tool=b["tool"], reason=b["error"]))
            elif b["max_err"] > 10.0 * 1.001:
                # Kept with its measurements so the figure can show it flagged; never
                # counted as a valid configuration (excluded from the Pareto front).
                corpus["general_gpu_excluded"].append(
                    dict(tool=b["tool"], label=BASELINE_LABELS[b["tool"]], cr=b["cr"],
                         compress_gbs=b["cmp_gbs"], decompress_gbs=b["dec_gbs"], max_err=b["max_err"],
                         reason=f"bound violated: max err {b['max_err']:.1f} > 10"))
            else:
                corpus["general_gpu"].append(dict(label=BASELINE_LABELS[b["tool"]], tool=b["tool"],
                                                  cr=b["cr"], compress_gbs=b["cmp_gbs"],
                                                  decompress_gbs=b["dec_gbs"], batches=b["batches"]))
        x2 = load(f"x2_{ds}_summary.json")
        assert x2["max_err"] <= 10.0 * 1.001, (ds, "X2 bound")
        corpus["fzgm_general"] = [dict(label="X2", tool=x2["tool"], cr=x2["cr"],
                                       compress_gbs=x2["compress_gbs"], decompress_gbs=x2["decompress_gbs"],
                                       specialized=bool(x2["installed"]), max_err=x2["max_err"],
                                       output_padding_elems=x2["output_padding_elems"])]
        payload["corpora"].append(corpus)

        md += [f"## {title}", "",
               "| configuration | bin | CR | compress GB/s (staged -> specialized) | decompress GB/s | specialized |",
               "|---|---|---:|---|---|---|"]
        for e in sorted(corpus["fzgm_all"], key=lambda e: (e["bin"], e["cr"])):
            c = (f"{e['compress_gbs_staged']:.0f} -> {e['compress_gbs_specialized']:.0f}" if e["specialized"]
                 else f"{e['compress_gbs_staged']:.0f}")
            d = (f"{e['decompress_gbs_staged']:.0f} -> {e['decompress_gbs_specialized']:.0f}"
                 if e["installed_groups"][1] else f"{e['decompress_gbs_staged']:.0f}")
            md.append(f"| FZGM {e['name']} | {e['bin']} | {e['cr']:.2f} | {c} | {d} | "
                      f"{'+'.join(e['implementation']) or 'no'} |")
        nr = corpus["native_roibin_sz"]
        md.append(f"| native ROIBIN-SZ, 1 core / 20 cores | 1 | {nr['cr']:.2f} | "
                  f"{nr['compress_gbs_1core']:.3f} / ~{nr['compress_gbs_20core']:.1f} | "
                  f"{nr['decompress_gbs_1core']:.3f} / ~{nr['decompress_gbs_20core']:.1f} | — |")
        n2 = corpus["native_roibin_sz_bin2"]
        md.append(f"| native ROIBIN-SZ, 1 core / 20 cores | 2 | {n2['cr']:.2f} | "
                  f"{n2['compress_gbs_1core']:.3f} / ~{n2['compress_gbs_20core']:.1f} | | — |")
        for g in corpus["general_gpu"]:
            md.append(f"| {g['tool']} (global eb 10, {g['batches']} batch) | — | {g['cr']:.2f} | "
                      f"{g['compress_gbs']:.0f} | {g['decompress_gbs']:.0f} | — |")
        for g in corpus["fzgm_general"]:
            md.append(f"| FZGM {g['tool']} (global eb 10, cross-family, not specialized) | — | {g['cr']:.2f} | "
                      f"{g['compress_gbs']:.0f} | {g['decompress_gbs']:.0f} | no |")
        for x in corpus["general_gpu_excluded"]:
            vals = (f"{x['cr']:.2f} | {x['compress_gbs']:.0f} | {x['decompress_gbs']:.0f}" if "cr" in x else " | | ")
            md.append(f"| ~~{x['tool']}~~ INVALID: {x['reason']} | — | {vals} | — |")
        md.append("")
    md += ["## Protocol and caveats", "",
           "- FZGM: whole-volume `fzgmod-cli -b --runs 7`, median warm device time; GPU verified idle "
           "before each cell. Every row: staged and specialized reconstructions byte-identical; ROI max "
           "error <= 10; bin=1 background max error <= 100 (+1e-6 float rounding).",
           "- bin=2 bins the background 2x2 and carries no background error bound (PSNR only).",
           "- Native ROIBIN-SZ: per-frame, LibPressio `roibin` + SZ3 3.3.0 (upstream-identical plugin "
           "code; frames passed as 3-D to avoid an upstream 2-D binning-inverse hang). 20-core figure "
           "= 20 x per-worker rate with 20 frame-parallel workers (generous to native); the conservative "
           "wall-time bound is in the JSON. SZ3's OpenMP mode gave no speedup on 9 MB frames. Native "
           "does not store peak coordinates in its archive (CR with an 8 B/peak table in the JSON).",
           "- General GPU compressors apply the ROI bound (abs 10) globally. Volumes are presented as "
           "one tall 2-D image; CXIDB 21 is split into two <2^31-byte batches because PFPL and cuSZ-Hi "
           "reject the 2.56 GB volume. Their throughput is each tool's own timing report.",
           "- lsCOMP (SC'25) has no pointwise or region bound and is reported in NOTES.md, not here.", ""]
    out.mkdir(parents=True, exist_ok=True)
    (out / "roibin_rq4.json").write_text(json.dumps(payload, indent=1))
    (out / "roibin_rq4.md").write_text("\n".join(md))
    print("wrote", out / "roibin_rq4.json")


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else
         Path.home() / "paper_organizer/projects/FZGM/evidence/publication/roibin")
