#!/usr/bin/env python3
"""Generate the paper-facing reconstruction-fidelity table.

Numeric cells come only from analyze_b1_fidelity.py JSON. Explanations and
semantic graph decompositions are reviewed source-level attribution, so a
measurement rerun cannot silently change them.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def difference(ratio: float) -> str:
    delta = (ratio - 1.0) * 100.0
    if abs(delta) < 0.5:
        return r"$\approx 0\%$"
    return rf"${delta:+.1f}\%$"


def load_pairs(path: Path) -> dict[str, dict]:
    payload = json.loads(path.read_text())
    return {row["id"]: row for row in payload["pairs"]}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fidelity", type=Path, required=True)
    parser.add_argument("--fsz-fidelity", type=Path, required=True)
    parser.add_argument("--pfpl-fidelity", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    measured = load_pairs(args.fidelity)
    measured.update(load_pairs(args.fsz_fidelity))
    if args.pfpl_fidelity:
        measured["pfpl"] = load_pairs(args.pfpl_fidelity)["pfpl"]
    required = {
        "cusz", "cuszhi_cr", "cuszhi_tp", "cuszp2_plain", "cuszp2_outlier",
        "cuszp3_plain", "cuszp3_outlier", "cuszp3_fixed", "pfpl", "fsz",
    }
    missing = sorted(required - measured.keys())
    if missing:
        raise ValueError(f"fidelity reports are missing required pairs: {missing}")

    def measured_difference(row_id: str) -> str:
        return difference(
            measured[row_id]["compressed_bytes_ratio_fzgm_over_native"]["geomean"]
        )

    # One row denotes one evaluated compressor pipeline or mode. WR and CC are
    # compatibility classes, not claims that specialization installed on every
    # dtype and geometry in the corpus.
    rows = [
        (
            "cuSZ",
            r"LorenzoQuant $\rightarrow$ Huffman",
            "---",
            measured_difference("cusz"),
            "Native selects a prebuilt Huffman codebook; FZGPUModules builds one per input.",
        ),
        (
            "cuSZ-Hi CR",
            r"See \Cref{fig:cuszhi-cr-graph}",
            "---",
            measured_difference("cuszhi_cr"),
            r"2-D uses 16$\times$16 rather than native 64$\times$64 tiles; Huffman partitioning differs.",
        ),
        (
            "cuSZ-Hi TP",
            r"G-Interp branches to codes: Zigzag $\rightarrow$ Bitshuffle $\rightarrow$ RRE; auxiliaries: Merge $\rightarrow$ Bitshuffle $\rightarrow$ RRE $\rightarrow$ RZE",
            "---",
            measured_difference("cuszhi_tp"),
            r"Denser 2-D anchors (16$\times$16 vs. native 64$\times$64); matched 3-D: $+1.4\%$.",
        ),
        (
            "cuSZp2 plain",
            r"Quantizer $\rightarrow$ Lorenzo $\rightarrow$ AdaptiveBitpack[plain]",
            "WR",
            measured_difference("cuszp2_plain"),
            "No material aggregate size difference.",
        ),
        (
            "cuSZp2 outlier",
            r"Quantizer $\rightarrow$ Lorenzo $\rightarrow$ AdaptiveBitpack[outlier]",
            "WR",
            measured_difference("cuszp2_outlier"),
            "Additional metadata byte preserves the full int32 rate range.",
        ),
        (
            "cuSZp3 fixed",
            r"Quantizer $\rightarrow$ TiledLorenzo[reorder] $\rightarrow$ AdaptiveBitpack[fixed]",
            "WR",
            measured_difference("cuszp3_fixed"),
            "1-D graphs omit the tile reorder.",
        ),
        (
            "cuSZp3 plain",
            r"Quantizer $\rightarrow$ TiledLorenzo $\rightarrow$ AdaptiveBitpack[plain]",
            "WR",
            measured_difference("cuszp3_plain"),
            "No material aggregate size difference.",
        ),
        (
            "cuSZp3 outlier",
            r"Quantizer $\rightarrow$ TiledLorenzo $\rightarrow$ AdaptiveBitpack[outlier]",
            "WR",
            measured_difference("cuszp3_outlier"),
            "Additional metadata byte preserves the full int32 rate range.",
        ),
        (
            "PFPL",
            r"Quantizer $\rightarrow$ Difference[Negabinary] $\rightarrow$ Bitshuffle $\rightarrow$ RZE",
            "CC",
            measured_difference("pfpl"),
            "Exact reconstruction; 32-bit chunk lengths and FZM framing add a small size overhead.",
        ),
        (
            "FSZ",
            r"Quantizer $\rightarrow$ AdaptiveLorenzo $\rightarrow$ AdaptiveBitpack[plain]",
            "---",
            measured_difference("fsz"),
            "Independent reimplementation; predictor-mode storage and framing differ.",
        ),
    ]

    lines = [
        "% Generated by compression_benchmarking/scripts/build_b1_port_table.py.",
        f"% Main fidelity manifest: {args.fidelity.resolve()}",
        f"% FSZ fidelity manifest: {args.fsz_fidelity.resolve()}",
        *(
            [f"% PFPL fidelity manifest: {args.pfpl_fidelity.resolve()}"]
            if args.pfpl_fidelity
            else []
        ),
        r"\begin{table*}[t]",
        r"  \centering",
        r"  \caption{FZGPUModules reconstructions of native designs. Each row is one",
        r"  evaluated pipeline; graphs are semantic rather than byte-identical. Spec. lists",
        r"  an available specialization (WR: warp-register; CC: chunk-cooperative; ---:",
        r"  staged-only). Size $\Delta$ is the geometric-mean complete-archive byte difference",
        r"  over jointly valid matches; negative values are smaller.}",
        r"  \label{tab:reconstruction-fidelity}",
        r"  \scriptsize",
        r"  \setlength{\tabcolsep}{2.5pt}",
        r"  \renewcommand{\arraystretch}{1.00}",
        r"  \begin{tabular}{@{}>{\raggedright\arraybackslash}p{0.095\textwidth}>{\raggedright\arraybackslash}p{0.36\textwidth}>{\centering\arraybackslash}p{0.045\textwidth}>{\raggedleft\arraybackslash}p{0.07\textwidth}>{\raggedright\arraybackslash}p{0.37\textwidth}@{}}",
        r"    \toprule",
        r"    Design & Declared FZGPUModules graph & Spec. & Size $\Delta$ & Key difference \\",
        r"    \midrule",
    ]

    for label, graph, spec, diff, caveat in rows:
        lines.extend([
            f"    {label}",
            f"      & {graph}",
            f"      & {spec}",
            f"      & {diff}",
            f"      & {caveat} \\\\",
        ])

    lines.extend([
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table*}",
        "",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
