#!/usr/bin/env python3
"""Publication artifact: X2 (LorenzoQuant-PFPL-ANS) vs tested native configurations at matched PSNR.

Per (dataset, field, target PSNR), paired within one session:
  - X2's compression ratio and compression throughput are interpolated to the target PSNR
    from its three sampled range-relative bounds (no extrapolation);
  - every native configuration is interpolated the same way;
  - the comparison native is the best-CR native whose interpolated compression throughput
    is >= X2's on that field ("equal or higher throughput");
  - gain = X2 CR / that native's CR.
A native that is invalid or cannot reach the target on a field drops out of that field
only. Fields where X2 cannot reach the target, or where no native is at least as fast as
X2, are counted separately and excluded from the gain statistics.

Inputs: the paired RQ3 X2 session (natives and X2 measured together); validity gating,
archive-size correction and interpolation are those of the exploratory mock-ups
(mockup_rq4_budget_and_design_space.py, mockup_x2_matched_quality.py).

    .venv/bin/python scripts/build_x2_matched_psnr.py [--out DIR]
"""
from __future__ import annotations

import argparse
import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

import mockup_rq4_budget_and_design_space as base  # noqa: E402
from mockup_x2_matched_quality import at, gmean  # noqa: E402

X2 = "x_lq_pfpl_ans"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=Path.home() /
                    "paper_organizer/projects/FZGM/evidence/publication/composition")
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    natives = list(base.NATIVES)
    curves = base.curves_from(base.NATIVE_SESSION, set(natives) | {X2})
    fields = defaultdict(set)
    for (d, f, v) in curves:
        fields[d].add(f)

    summary, per_field = [], []
    for d in sorted(fields):
        for t in base.TARGETS_DB:
            gains, x2_unreached, no_faster, n_fields = [], 0, 0, len(fields[d])
            comparators = defaultdict(int)
            for f in sorted(fields[d]):
                xc = curves.get((d, f, X2))
                xa = at(xc, t) if xc else None
                if not xa:
                    x2_unreached += 1
                    continue
                x_cr, x_tp = 32.0 / xa[0], xa[1]
                best = None
                for v in natives:
                    c = curves.get((d, f, v))
                    p = at(c, t) if c else None
                    if not p:
                        continue
                    cr, tp = 32.0 / p[0], p[1]
                    if tp >= x_tp and (best is None or cr > best[1]):
                        best = (v, cr, tp)
                if best is None:
                    no_faster += 1
                    per_field.append(dict(dataset=d, field=f, target_db=t, x2_cr=x_cr, x2_tp=x_tp,
                                          comparator=None, gain=None))
                    continue
                g = x_cr / best[1]
                gains.append(g)
                comparators[base.LABEL.get(best[0], best[0])] += 1
                per_field.append(dict(dataset=d, field=f, target_db=t, x2_cr=x_cr, x2_tp=x_tp,
                                      comparator=best[0], comparator_cr=best[1], comparator_tp=best[2],
                                      gain=g))
            summary.append(dict(
                dataset=d, target_db=t, fields=n_fields, compared=len(gains),
                x2_cannot_reach_target=x2_unreached, x2_faster_than_every_native=no_faster,
                gmean_gain=gmean(gains) if gains else None,
                median_gain=statistics.median(gains) if gains else None,
                min_gain=min(gains) if gains else None, max_gain=max(gains) if gains else None,
                fields_gain_above_1=sum(g > 1.0 for g in gains),
                comparators=dict(sorted(comparators.items(), key=lambda kv: -kv[1]))))

    payload = dict(session=base.NATIVE_SESSION.name, composition=X2, natives=natives,
                   targets_db=list(base.TARGETS_DB), summary=summary, per_field=per_field)
    (args.out / "x2_matched_psnr.json").write_text(json.dumps(payload, indent=1))

    md = ["# X2 vs tested native configurations at matched PSNR", "",
          f"Session `{base.NATIVE_SESSION.name}` (X2 and natives paired). Generated by "
          "`compression_benchmarking/scripts/build_x2_matched_psnr.py`. Per field and target "
          "PSNR: X2 and each native are interpolated from three range-relative bounds (no "
          "extrapolation); X2's CR is divided by the best CR among natives with equal or higher "
          "compression throughput on that field. Gains are geometric means over compared fields. "
          "Natives invalid on a field drop out of that field only.", "",
          "| Dataset | PSNR | Fields | Compared | X2 can't reach | X2 faster than all | gmean gain | median | range | gain > 1 | most frequent comparator |",
          "|---|---:|---:|---:|---:|---:|---:|---:|---|---:|---|"]
    for s in summary:
        g = (lambda x: f"{x:.2f}x" if x is not None else "--")
        comp = next(iter(s["comparators"]), "--")
        md.append(f"| {s['dataset']} | {s['target_db']:.0f} dB | {s['fields']} | {s['compared']} | "
                  f"{s['x2_cannot_reach_target']} | {s['x2_faster_than_every_native']} | {g(s['gmean_gain'])} | "
                  f"{g(s['median_gain'])} | {g(s['min_gain'])}--{g(s['max_gain'])} | "
                  f"{s['fields_gain_above_1']}/{s['compared']} | {comp} |")
    (args.out / "x2_matched_psnr.md").write_text("\n".join(md) + "\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
