#!/usr/bin/env python3
"""Generate the compact paper-facing B1 port comparison table.

The numeric cells come only from analyze_b1_fidelity.py JSON. Explanations are
kept here as reviewed implementation attribution, so rerunning measurements
cannot silently replace a source-level conclusion.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROW_ORDER = [
    "cusz", "cuszhi", "cuszp2_plain", "cuszp2_outlier", "cuszp3_plain",
    "cuszp3_outlier", "cuszp3_fixed", "fzgpu", "pfpl",
]

REASONS = {
    "cusz": (
        "FZGM uses a separately adapted Huffman implementation and FZM framing; "
        "the size contribution of each has not been isolated."
    ),
    "cuszhi": (
        "The 2-D GInterp geometry differs to avoid an upstream anchor-gather "
        "defect; CR size and quality use one fresh process per call because repeated reuse is unsafe."
    ),
    "cuszp2_plain": "---",
    "cuszp2_outlier": (
        "FZGM stores an additional selection byte per 32-value block rather than packing "
        "the selection into the native rate byte."
    ),
    "cuszp3_plain": "---",
    "cuszp3_outlier": (
        "FZGM stores an additional selection byte per 64-value tile rather than packing "
        "the selection into the native rate byte."
    ),
    "cuszp3_fixed": (
        "Dimension-correct streams match except on QMCPACK, where FZGM is "
        "1.8--4.3\\% smaller; the cause is not isolated."
    ),
    "fzgpu": (
        "The BitplaneRZE kernels are adapted from FZ-GPU, but FZGM uses a separate "
        "quantizer, staged execution, and FZM framing."
    ),
    "pfpl": (
        "The native fused and FZGM staged implementations have field-dependent "
        "size differences that cancel in the aggregate."
    ),
}

LABELS = {
    "cusz": "cuSZ",
    "cuszhi": "cuSZ-Hi (CR/TP)",
    "cuszp2_plain": "cuSZp2 plain",
    "cuszp2_outlier": "cuSZp2 outlier",
    "cuszp3_plain": "cuSZp3 plain",
    "cuszp3_outlier": "cuSZp3 outlier",
    "cuszp3_fixed": "cuSZp3 fixed",
    "fzgpu": "FZ-GPU",
    "pfpl": "PFPL",
}


def difference(ratio: float) -> str:
    pct = abs(ratio - 1.0) * 100.0
    if pct < 0.5:
        return "No aggregate difference"
    direction = "smaller" if ratio < 1.0 else "larger"
    return rf"{pct:.1f}\% {direction}"


def quality_caveat(rows: list[dict], *, corrected_2d: bool = False) -> str:
    native = sum(int(row["reference_severe_bound_violation"]) for row in rows)
    fzgm = sum(int(row["reconstruction_severe_bound_violation"]) for row in rows)
    parts: list[str] = []
    if native:
        parts.append(
            f"{native} paired native bound violation{'s' if native != 1 else ''}"
        )
    if fzgm:
        parts.append(f"{fzgm} FZGM bound violation{'s' if fzgm != 1 else ''}")
    if corrected_2d:
        parts.append("2-D predictor differs")
    return "; ".join(parts) if parts else "---"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fidelity", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    payload = json.loads(args.fidelity.read_text())
    measured = {row["id"]: row for row in payload["pairs"]}
    required = {
        "cusz", "cuszhi_cr", "cuszhi_tp", "cuszp2_plain", "cuszp2_outlier",
        "cuszp3_plain", "cuszp3_outlier", "cuszp3_fixed", "fzgpu", "pfpl",
    }
    missing = sorted(required - measured.keys())
    if missing:
        raise ValueError(f"fidelity report is missing required pairs: {missing}")

    lines = [
        "% Generated by compression_benchmarking/scripts/build_b1_port_table.py.",
        f"% Fidelity manifest: {args.fidelity.resolve()}",
        r"\begin{table*}[t]",
        r"  \centering",
        r"  \caption{Compressed-size differences between FZGM pipelines and their native",
        r"  implementations, computed from geometric-mean compressed bytes over jointly valid",
        r"  matched runs. Quality caveats identify severe error-bound violations or known",
        r"  implementation differences. A dash indicates no material caveat or identified cause.}",
        r"  \label{tab:port-accuracy}",
        r"  \footnotesize",
        r"  \setlength{\tabcolsep}{4pt}",
        r"  \renewcommand{\arraystretch}{1.08}",
        r"  \begin{tabular}{@{}p{0.14\textwidth}p{0.18\textwidth}p{0.22\textwidth}p{0.39\textwidth}@{}}",
        r"    \toprule",
        r"    Pipeline & Compressed-size difference & Quality caveat & Reason \\",
        r"    \midrule",
    ]

    for row_id in ROW_ORDER:
        if row_id == "cuszhi":
            cr, tp = measured["cuszhi_cr"], measured["cuszhi_tp"]
            rows = [cr, tp]
            diff = (
                f"CR: {difference(cr['compressed_bytes_ratio_fzgm_over_native']['geomean'])}; "
                f"TP: {difference(tp['compressed_bytes_ratio_fzgm_over_native']['geomean'])}"
            )
        else:
            rows = [measured[row_id]]
            diff = difference(rows[0]["compressed_bytes_ratio_fzgm_over_native"]["geomean"])
        caveat = quality_caveat(rows, corrected_2d=(row_id == "cuszhi"))
        if row_id == "cuszhi" and any(
            int(row["reference_severe_bound_violation"]) for row in rows
        ):
            caveat = "Native bound violation in both modes; 2-D predictor differs"
        lines.extend([
            f"    {LABELS[row_id]}",
            f"      & {diff}",
            f"      & {caveat}",
            f"      & {REASONS[row_id]} \\\\",
        ])

    lines.extend([
        r"    \bottomrule",
        r"  \end{tabular}",
        r"\end{table*}",
        "",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
