#!/usr/bin/env python3
"""Extract FZGM Lorenzo quant codes as a derived uint16 dataset.

Why this exists
---------------
The nvCOMP comparison has two framings (docs/adapters/nvcomp.md). This script
builds the input for the second one, **back-end isolation**.

FZGM's `gpu_zstd` preset is an error-bounded lossy compressor: LorenzoQuant
predicts and quantizes, then GPULZ + Huffman + ANS losslessly code the result.
nvCOMP's Zstd is only the second half of that — a lossless byte coder. Comparing
end to end therefore measures the Lorenzo predictor, not the two Zstd
implementations. To compare the coders themselves, both have to be handed the
same bytes: the quant codes.

So: run a predictor-only pipeline (LorenzoQuant, no coder), pull the `codes`
output port straight out of the .fzm archive, and write it as a raw uint16 file.
That file becomes a derived dataset both `nvcomp` and FZGM's coder-only pipeline
consume under `error.mode: lossless`.

What is and isn't in the codes stream
-------------------------------------
Only the `codes` port. LorenzoQuant also emits `outlier_errors` / `outlier_indices`
for values its prediction could not represent within the bound; those are carried
identically by both back ends and are not part of what is being compared, so they
are excluded — and their count is reported, because a field with many outliers has
a codes stream that represents less of the original data. A ratio measured on this
derived dataset is a **back-end** ratio and must never be quoted as a compression
ratio for the field.

Usage
-----
    python scripts/extract_quant_codes.py --dataset CESM-2D --field CLDHGH --eb 1e-3
    python scripts/extract_quant_codes.py --dataset CESM-2D --fields all --eb 1e-3
    python scripts/extract_quant_codes.py --dataset NYX --field temperature \\
        --eb 1e-4 --mode REL --radius 2048 --out-root /media/volume/derived

Writes <out-root>/<dataset>_qcodes_<mode><eb>/<field>.u16 and prints a
configs/datasets.yaml stanza to paste in.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from benchkit.config import DatasetCatalog          # noqa: E402
from benchkit.fzm import FzmArchive, FzmError       # noqa: E402
from benchkit.site import Site                      # noqa: E402

REPO = Path(__file__).resolve().parent.parent

# Predictor only: one stage, no coder. quant_radius/zigzag match gpu_zstd.toml so
# the codes are the ones that preset's back end would actually see.
_TEMPLATE = """\
# Generated by scripts/extract_quant_codes.py — predictor only, no coder.
memory_strategy = "PREALLOCATE"

[[stage]]
name = "lrz"
type = "LorenzoQuant"
input_type = "{fzgm_dtype}"
code_type = "uint16"
error_bound = {eb!r}
error_bound_mode = "{mode}"
quant_radius = {radius}
outlier_capacity = 0.2
zigzag_codes = true
"""

_FZGM_DTYPE = {"f32": "float32", "f64": "float64"}


def extract_one(cli: str, field, eb: float, mode: str, radius: int,
                out_path: Path, keep_work: Path | None = None) -> dict:
    """Run the predictor-only pipeline on one field; write its codes port."""
    work = Path(tempfile.mkdtemp(prefix="qcodes-")) if keep_work is None else keep_work
    work.mkdir(parents=True, exist_ok=True)
    try:
        cfg = work / "lrz_only.toml"
        cfg.write_text(_TEMPLATE.format(
            fzgm_dtype=_FZGM_DTYPE[field.dtype], eb=eb, mode=mode, radius=radius))

        archive = work / "lrz.fzm"
        argv = [cli, "-c", str(cfg), "-i", str(field.path),
                "-l", field.dim_arg, "-t", field.dtype, "-z", "-o", str(archive)]
        proc = subprocess.run(argv, capture_output=True, text=True)
        if proc.returncode != 0:
            raise RuntimeError(
                f"{field.dataset}/{field.field}: fzgmod-cli exited {proc.returncode}\n"
                f"$ {' '.join(argv)}\n{proc.stdout}\n{proc.stderr}")

        arc = FzmArchive.read(archive)
        codes = arc.port("codes")
        if codes.data_type != "u16":
            raise FzmError(
                f"{field.dataset}/{field.field}: codes port is {codes.data_type}, "
                f"expected u16 — did code_type change in the template?")

        # LorenzoQuant emits one code per input element. If that does not hold, the
        # derived dataset's dims would silently disagree with its contents and every
        # downstream row would be measured against the wrong element count.
        n_codes = codes.data_size // 2
        if n_codes != field.num_elements:
            raise FzmError(
                f"{field.dataset}/{field.field}: codes port holds {n_codes} uint16 "
                f"codes but the field has {field.num_elements} elements. The derived "
                f"dataset's dims would be wrong; refusing to write it.")

        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(arc.read_port("codes"))

        # Outliers are excluded by design (see the module docstring) — report how
        # much of the field they account for so a lopsided one is visible.
        n_outliers = arc.port("outlier_indices").data_size // 4
        return {
            "field": field.field,
            "elements": field.num_elements,
            "bytes": out_path.stat().st_size,
            "outliers": n_outliers,
            "outlier_frac": n_outliers / field.num_elements if field.num_elements else 0.0,
        }
    finally:
        if keep_work is None:
            shutil.rmtree(work, ignore_errors=True)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Extract FZGM Lorenzo quant codes as a derived uint16 dataset.")
    ap.add_argument("--dataset", required=True, help="dataset name in configs/datasets.yaml")
    ap.add_argument("--field", help="one field name")
    ap.add_argument("--fields", help="'all', or a comma-separated list")
    ap.add_argument("--eb", type=float, default=1e-3, help="error bound (default 1e-3)")
    ap.add_argument("--mode", default="NOA", choices=["NOA", "REL", "ABS"],
                    help="FZGM native bound mode. NOA = range-relative, the "
                         "cross-tool comparable (default). REL = eb*max|data|.")
    ap.add_argument("--radius", type=int, default=2048,
                    help="quant_radius; matches gpu_zstd.toml (default 2048)")
    # Default under BENCHKIT_DATA_ROOT so configs/datasets.yaml can reference the
    # result as ${BENCHKIT_DATA_ROOT}/derived/... and stay portable across sites.
    ap.add_argument("--out-root",
                    help="output root (default: $BENCHKIT_DATA_ROOT/derived)")
    ap.add_argument("--catalog", default=str(REPO / "configs/datasets.yaml"))
    ap.add_argument("--cli", help="fzgmod-cli path (default: FZGMOD_CLI / site config)")
    ap.add_argument("--force", action="store_true", help="overwrite existing outputs")
    args = ap.parse_args()

    if bool(args.field) == bool(args.fields):
        ap.error("pass exactly one of --field or --fields")

    cli = args.cli or Site.load().fzgmod_cli
    if not cli or not Path(cli).exists():
        print(f"error: fzgmod-cli not found (tried {cli!r}). Set FZGMOD_CLI or --cli.",
              file=sys.stderr)
        return 2

    catalog = DatasetCatalog.load(args.catalog)
    if args.field:
        names = [args.field]
    elif args.fields == "all":
        names = catalog.fields(args.dataset)
    else:
        names = [n.strip() for n in args.fields.split(",") if n.strip()]

    out_root = Path(args.out_root or
                    Path(os.environ.get("BENCHKIT_DATA_ROOT", REPO / "data")) / "derived")
    tag = f"{args.mode.lower()}{args.eb:g}"
    out_dir = out_root / f"{args.dataset}_qcodes_{tag}"

    print(f"fzgmod-cli: {cli}")
    print(f"output:     {out_dir}")
    print(f"predictor:  LorenzoQuant eb={args.eb:g} mode={args.mode} radius={args.radius}\n")

    results, failures = [], []
    for name in names:
        out_path = out_dir / f"{name}.u16"
        if out_path.exists() and not args.force:
            print(f"  skip  {name}  (exists; --force to overwrite)")
            continue
        try:
            field = catalog.resolve(args.dataset, name)
            info = extract_one(cli, field, args.eb, args.mode, args.radius, out_path)
        except Exception as e:                       # noqa: BLE001
            failures.append((name, str(e)))
            print(f"  FAIL  {name}: {e}", file=sys.stderr)
            continue
        results.append((field, info))
        print(f"  ok    {name}  {info['elements']} codes, {info['bytes']} bytes, "
              f"{info['outliers']} outliers ({info['outlier_frac']:.4%})")

    if not results:
        print("\nnothing written.", file=sys.stderr)
        return 1 if failures else 0

    # The catalog stanza. dims are the ORIGINAL field's dims: one code per element,
    # and the coder-only pipelines are 1-D over bytes anyway, so the shape is
    # carried purely so the harness knows the element count.
    print(f"\n--- paste into configs/datasets.yaml ---\n")
    print(f"# Derived: FZGM LorenzoQuant codes from {args.dataset} at "
          f"{args.mode} eb={args.eb:g}, radius={args.radius}.")
    print(f"# Generated by scripts/extract_quant_codes.py. Lossless runs only — a CR")
    print(f"# measured on these is a BACK-END ratio, not a ratio for the field.")
    print(f"{args.dataset}-qcodes-{tag}:")
    print(f"  dtype: u16")
    print(f"  dim_order: fast-to-slow")
    print(f"  root: {out_dir}")
    print(f"  fields:")
    for field, _ in results:
        dims = "[" + ", ".join(str(d) for d in field.dims) + "]"
        print(f"    {field.field}: {{dims: {dims}, path: {field.field}.u16}}")

    if failures:
        print(f"\n{len(failures)} field(s) failed:", file=sys.stderr)
        for name, err in failures:
            print(f"  {name}: {err.splitlines()[0]}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
